function [ figure1 ] = plot_joint_error(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 27-May-2012 21:50:32

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','s:16');
set(plot1(2),'DisplayName','s:32');
set(plot1(3),'DisplayName','s:64');
set(plot1(4),'LineStyle','--','DisplayName','c:16');
set(plot1(5),'LineStyle','--','DisplayName','c:32');
set(plot1(6),'LineStyle','--','DisplayName','c:64');

% Create xlabel
xlabel('Boosting Round','FontSize',14);

% Create ylabel
ylabel('Test Error','FontSize',14);

% Create title
title('Comparing Convergence: Stumps vs. Stump Chains','FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.747647887886639 0.530616391268409 0.135745978924016 0.366465682745381]);

