function [ figure1 ] = plot_test_error(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-May-2012 01:32:43

% Create figure
figure1 = figure('XVisual',...
    '0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot(YMatrix1,'LineWidth',2,'Parent',axes1);

% Create xlabel
xlabel('Boosting Round','FontSize',14);

% Create ylabel
ylabel('Test Error','FontSize',14);

% Create title
title('Test Error Convergence','FontSize',14);

